### ISSUE TITLE
writePoint callback(err, response) return 'null', 'undefined'

### ISSUE THREAD

**Issue by teckays** [node-influx/node-influx#100]
The callback from `writePoint` method return `err=null` and `response=undefined`

**Comment by mauvm** [comment]
I also have this problem.

**Comment by bencevans** [comment]
Thanks for the research @mauvm.

**Comment by mauvm** [comment]
It seems that I had a different problem. The data was not being inserted because I was giving the time in seconds (with the `precision=s` flag). However this currently is not supported (yet) in v0.9 (https://goo.gl/s60Lhy).

The `204 No Content` response is what is expected. `node-influx` parses the response body and returns an error or `body.results`. Since the response is a `204` values `err=null` and `response=undefined` is what you should expect. `response` only contains data when querying InfluxDB.

**Comment by grydstedt** [comment]
I'm hitting "body is undefined" error being thrown by the lib with 204 response on writePoint. Is 204 a valid response code from InfluxDB? If so that error shouldn't be thrown?

**Comment by connor4312** [comment]
@grydstedt Can you post the stacktrace?

**Comment by grydstedt** [comment]
@connor4312 Think I was running an outdated version of InfluxDB

**Comment by connor4312** [comment]
Okay, feel free to reopen if it's still an issue 😄

**Comment by dandv** [comment]
Does `reponse` EVER contain anything? It's always undefined for me, whether there's an error or not, for both `writePoint` and `writePoints`.

What should `response` look like?

**Comment by mauvm** [comment]
@dandv There is no response when writing data. I don't know the exact response format, but you can find it out by using the `queryDB` method.
