### ISSUE TITLE
Strange problem in many write point calls

### ISSUE THREAD

**Issue by rodrigoapereira** [node-influx/node-influx#106]
I'm running many writePoint calls with node-influx and many cases InfluxDB returns 500 and timeout. But, i try execute same query with request and InfluxDB returns successfully.

It seems to be something related with pool option in request.

Test Case: https://gist.github.com/rodrigoapereira/9a74cb1275d8606fdfcf
Can anyone help me?

Node Version: v0.10.37
Request Version: request@2.64.0
Node-Influx Version: influx@4.0.1
InfluxDB Version: 0.9.4.2

**Comment by SamuelToh** [comment]
Hey 

I think there is a writePoints API which you can use for bulk insertion. I think the port that you are using for talking to influx is getting flooded with requests through the loop, which is why you are seeing errors like time out.

You can checkout how to do bulk insert through their examples, see README.md or test.js.
