### ISSUE TITLE
npm has old version 4.0.1 of node-influx

### ISSUE THREAD

**Issue by GermanBluefox** [node-influx/node-influx#118]
Actual npm packet has not all fixes. E.g. 
https://github.com/node-influx/node-influx/commit/391d4d4de2c2e109854573fda30b32f20218cb02
is not included.

Can you create 4.1.0  and publish it?

**Comment by bencevans** [comment]
Hi @GermanBluefox 

An issue with one of the tests has crept into master as seem on https://travis-ci.org/node-influx/node-influx/jobs/94170711 which needs to be rectified before publishing a new version. Once that's fixed and merged into master we'll get a release up!

I'm unable to look into it at the minute, if you're able to and can create a pull-request it would be much appreciated. Else if this bug won't affect your project then I'd suggest pinning your influx dependency to a pinned commit (e.g `391d4d4` from your example or `a4b6302` being the latest master commit) of this repository rather than using the version from npm's registry.

Cheers

Ben

**Comment by bencevans** [comment]
An example of a pinned git dependency in package.json:

    "soda": "git://github.com/LearnBoost/soda.git#941b5ee6a1302089b3b00600b49b52e6569e4b0b",

**Comment by GermanBluefox** [comment]
I cannot reproduce your problem:
![image](https://cloud.githubusercontent.com/assets/4582016/11912515/4aa91c90-a640-11e5-9712-3ce48d3ba31c.png)
May be influxdb fixed the bug?

**Comment by bencevans** [comment]
Using the same version as the Travis test suite the test suite won't pass,
what version of Influx are you using please?

**Comment by bencevans** [comment]
We've pushed a new release! Checkout `v4.1.0`.
