### ISSUE TITLE
Issues with tags containing special chars (space and comma)

### ISSUE THREAD

**Issue by oshoemaker** [node-influx/node-influx#123]
I am attempting to sanitize data going into influx using this module. I can sanitize the data in my abstraction but was curious if there was any interest in doing this in the module itself.  It seems that there is some done for the name but not for the content that is going into influx:

var line = seriesName.replace(/ /g, '\\ ').replace(/,/g, '\\,')

Something similar should probably be done for the tags as well. I am happy to implement this if the maintainers are open to the idea.

**Comment by oshoemaker** [comment]
In addition, the above referenced regex seems to be flawed. It doesn't contain errors but I don't think that it will catch what you want it to.  The functional regex should look something like this:

.replace(/\s/g, '\\ ').replace(/,/g, '\\,');

Unless I am missing something

**Comment by bencevans** [comment]
I'm afraid I've not been using Influx recently so don't want to go pointing in
the wrong direction. Hopefully someone else from the community will be able to
help.

  

I'm reluctant to add too much serialisation etc. in this library so that
people can access the "raw" data and doesn't conflict with systems written
with other libraries communicating with Influx. I believe serialisation should
done by higher level abstractions such as Object Data Mappers if that
functionality is required.

  

My aim with node-influx has always been to keep as close to just the API
wrapper as possible, but handling a few things like server failover (thanks to
contributors!).

> On Mar 18 2016, at 9:15 pm, oshoemaker &lt;notifications@github.com&gt;
wrote:  

>

> In addition, the above referenced regex seems to be flawed. It doesn't
contain errors but I don't think that it will catch what you want it to. The
functional regex should look something like this:

>

> .replace(/\s/g, '\ ').replace(/,/g, '\,');

>

> Unless I am missing something

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/node-
influx/node-influx/issues/123#issuecomment-198544623)![](https://github.com/no
tifications/beacon/AAm-R5g2pprkMWhbO6VSnGIyPVWe0hACks5puxXwgaJpZM4H0Ijk.gif)

**Comment by oshoemaker** [comment]
My only issue with the lack of sanitization is that it is done in some places and not in others. The inconsistencies cause confusion as it works in one place and not in another. It is only documented in code and isn't clear when using the module. 

- Owen

**Comment by bencevans** [comment]
Agreed, that's not a good state. I'm sorry but I can't dedicate time to this
project now. I'd be happy to add someone that's willing to maintain it, just
drop me an email!

> On Mar 20 2016, at 5:14 pm, oshoemaker &lt;notifications@github.com&gt;
wrote:  
My only issue with the lack of sanitization is that it is done in some places
and not in others. The inconsistencies cause confusion as it works in one
place and not in another. It is only documented in code and isn't clear when
using the module.  
  
\- Owen  
  
&gt; On Mar 20, 2016, at 8:21 AM, Ben Evans &lt;notifications@github.com&gt;
wrote:  
&gt;  
&gt; I'm afraid I've not been using Influx recently so don't want to go
pointing in  
&gt; the wrong direction. Hopefully someone else from the community will be
able to  
&gt; help.  
&gt;  
&gt;  
&gt;  
&gt; I'm reluctant to add too much serialisation etc. in this library so that  
&gt; people can access the "raw" data and doesn't conflict with systems
written  
&gt; with other libraries communicating with Influx. I believe serialisation
should  
&gt; done by higher level abstractions such as Object Data Mappers if that  
&gt; functionality is required.  
&gt;  
&gt;  
&gt;  
&gt; My aim with node-influx has always been to keep as close to just the API  
&gt; wrapper as possible, but handling a few things like server failover
(thanks to  
&gt; contributors!).  
&gt;  
&gt; &gt; On Mar 18 2016, at 9:15 pm, oshoemaker
&amp;lt;notifications@github.com&amp;gt;  
&gt; wrote:  
&gt;  
&gt; &gt;  
&gt;  
&gt; &gt; In addition, the above referenced regex seems to be flawed. It
doesn't  
&gt; contain errors but I don't think that it will catch what you want it to.
The  
&gt; functional regex should look something like this:  
&gt;  
&gt; &gt;  
&gt;  
&gt; &gt; .replace(/\s/g, '\ ').replace(/,/g, '\,');  
&gt;  
&gt; &gt;  
&gt;  
&gt; &gt; Unless I am missing something  
&gt;  
&gt; &gt;  
&gt;  
&gt; &gt; —  
&gt; You are receiving this because you are subscribed to this thread.  
&gt; Reply to this email directly or [view it on
GitHub](https://github.com/node-  
&gt; influx/node-
influx/issues/123#issuecomment-198544623)![](https://github.com/no  
&gt; tifications/beacon/AAm-
R5g2pprkMWhbO6VSnGIyPVWe0hACks5puxXwgaJpZM4H0Ijk.gif)  
&gt;  
&gt; —  
&gt; You are receiving this because you authored the thread.  
&gt; Reply to this email directly or view it on GitHub  
&gt;  

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/node-
influx/node-influx/issues/123#issuecomment-198966849)![](https://github.com/no
tifications/beacon/AAm-R7OSA1nBZHvb0wjDWRceG0koB2lYks5pvYB2gaJpZM4H0Ijk.gif)

**Comment by connor4312** [comment]
Resolved in 4.x with recent PRs by multiple contributors, and in 5.x.
