### ISSUE TITLE
"unbalanced quotes" when writing points with '\"'

### ISSUE THREAD

**Issue by nonsenz** [node-influx/node-influx#145]
hi,

not sure if i am doing it wrong but

    influxClient.writePoint("status", {foo: 'bar\"'},{}, function(err,dat){
        if (err || dat ) {
            console.log(err, dat);    
        }
    });

returns
 
    Error: {"error":"unable to parse 'status foo=\"bar\"\"': unbalanced quotes"}

even setting the value to `'bar\"'` gives me the error
shouldn't this work?

btw. i am using `"influx": "^4.2.0"`

**Comment by SPARTAN563** [comment]
Hi Sascha,

If you attempt specifying it as `{ foo: 'bar\\\"' }` does it work correctly? I suspect there isn't any escaping going on in the library and it's passing the `"` directly through to Influx, causing it to fail.

**Comment by nonsenz** [comment]
hi and thx for your reply,
yea that works and i thought of your suggestion. but as i do not know what content my service writes to influx (the content is generated in other services) that's kind of sad. shouldn't it be the concern of this client to ensure this doesn't happen? 
what i can do is recursively scan my values and replace/encode this by my self.

**Comment by SPARTAN563** [comment]
Yeah, was just a way of diagnosing the source of the issue - I don't have the time right now to add the fix, so if someone else could hop in I'd appreciate it, otherwise I'll see if I can get to it tomorrow or next week.

That being said, it should simply be a matter of running `value.replace('\\', '\\\\').replace('\"', '\\\"')` to escape double quotes.

**Comment by nonsenz** [comment]
thx for your suggestion and your superior support :-)
