### ISSUE TITLE
Plan for promises

### ISSUE THREAD

**Issue by sickDevelopers** [node-influx/node-influx#165]
Is there any plan for implementing Promises logic instead of callbacks in near future?

**Comment by bencevans** [comment]
I would love to have promises in there, I've been messing with async
keyword features and would love to have it in but started a new job today
so don't see myself getting to mess with it soon. If anyone's up for giving
it a shot pull requests are much loved!

**Comment by sickDevelopers** [comment]
Great, since I'm working on a project implementing your library, I think I can fork the project and start working on that.
 
If anyone else is reading this, any help is welcome.

Thank you for your work 'till now

**Comment by dandv** [comment]
@connor4312: would be great to have Promises instead of callbacks in v5. That would also open open the door to using async/await, which is far, far cleaner than callbacks.

I've been trying to migrate a large measurement to another one via node-influx (because InfluxDB's support for null handling is non-existent), and ended up having to call the migrate function recursively for each chunk (similar to the second example [here](stevehanov.ca/blog/?id=127)). That's a recipe for disaster.

I'd be happy to help, and would support pushing the release date in order to get Promises in.

**Comment by connor4312** [comment]
I agree. Let's do this.

**Comment by connor4312** [comment]
Resolved in https://github.com/node-influx/node-influx/commit/81245b0f1fba279bd3268ccb371e3eb8aca8a51f, it'll be in 5.x

**Comment by connor4312** [comment]
These changes have been published in `5.0.0-alpha.1`. You can install this via:

```
npm install --save influx@next
```

**Comment by dandv** [comment]
Happy to report that replacing my promisifying wrapper of old node-influx v4 module with v5 has been painless, and I'm seeing a 20% performance improvement.
