### ISSUE TITLE
Build functional tests against InfluxDB 1.0

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#192]
I've ran the tests against

    sudo docker run -d -p 8083:8083 -p 8086:8086 --expose 8090 --expose 8099 influxdb

(after modifying the version checking code in test.js), and all tests passed.

**Comment by connor4312** [comment]
A bit of a todo here: I want to continue testing most of the business functionality in unit tests, like the current 5.0 branch does, but getting functional tests running again would be great. However, the functional tests in 4.x weren't too spectacular: they were intended to test the library itself, and didn't always verify that the library was reading or writing the right things.

Rather I want 5.x functional tests to be focused on testing the _assumptions_ the library makes about Influx, not the mechanics of the package.

**Comment by connor4312** [comment]
First integration tests are running via the inflxudb Docker image on the [integration-tests](https://github.com/node-influx/node-influx/tree/integration-tests) branch. Also started using their Docker to develop locally; their OSX experienced has improve dramatically since I last gave it a shot, it's now as easy as running services via Homebrew (easier even, when dealing with multiple versions). Very smooth, very nice.

**Comment by connor4312** [comment]
Fixed in https://github.com/node-influx/node-influx/pull/223
