### ISSUE TITLE
Add browser tests for timing out long queries

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#208]
No need to create terabyte-sized series; use this [bespoke bug](https://github.com/influxdata/influxdb/issues/7426).

**Comment by connor4312** [comment]
Are you just after a way to test the timeout behaviour? If so, we can use a "fake" Influx server (that's actually what the [5.x tests do](https://github.com/node-influx/node-influx/blob/5.0.0/test/unit/pool.test.ts#L133)) instead of relying on a bug in Influx.

Also, neat link to the sample data! Looks like a new addition to their docs in 1.0, I'll make use of that.

**Comment by dandv** [comment]
If there's already a timing out server, let's use that, of course.

I just had to find a silver lining in that annoying InfluxDB bug that wasted my whole evening :)
