### ISSUE TITLE
Allow measurements' default precisions to be defined in Schemas

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#219]
Some feedback on the `epoch` property of [QueryOptions](https://node-influx.github.io/typedef/index.html#static-typedef-QueryOptions):
- the name `epoch` suggests an instance in time rather than precision, and might lead one to think they can override the [UNIX epoch](https://en.wikipedia.org/wiki/Epoch_%28reference_date%29)
- since it's optional, the default should be mentioned
- can this precision be set at a higher level than QueryOptions? It feels like a measurement or SchemaOptions property to me, affecting both QueryOptions and [WriteOptions](https://node-influx.github.io/typedef/index.html#static-typedef-WriteOptions) equally. I'd rather set it once, and not have to repeat it in every query/queryRaw.

**Comment by connor4312** [comment]
- I was mirroring what Influx takes in their query string, but as a 'black box' it would make more sense to simply call it `precision`, I agree
 - Yep
 - I agree! I actually put a brief [question](https://gitter.im/influxdata/influxdb?at=5803ff8e8eaaaea366a037e7) in the (sadly inactive) InfluxDB gitter last night to see if anyone would have a use case for which making it a Schema option is undesirable

**Comment by dandv** [comment]
Never knew about Gitter. I've had a lot more luck [making a fuss in their GitHub issues](https://github.com/influxdata/influxdb/issues?utf8=%E2%9C%93&q=author%3Adandv%20) :)

**Comment by connor4312** [comment]
>the name epoch suggests an instance in time rather than precision, and might lead one to think they can override the UNIX epoch
> since it's optional, the default should be mentioned

Done in https://github.com/node-influx/node-influx/commit/f46e03a2c0445da2584897f1b157ce4719808393

> It feels like a measurement or SchemaOptions property to me, affecting both QueryOptions and WriteOptions equally. I'd rather set it once, and not have to repeat it in every query/queryRaw.

On this, it becomes a bit more challenging. At a protocol level a single `query` can read across multiple measurements and a single `.write` can read across multiple measurements, but the precision is set for the entire request. This can be overcome with some manual conversion in the `.write` method--writing to a timestamp `1` in millisecond precision is equivalent to writing a timestamp `1000` in microsecond precision--but for querying determining which schemas are being read from ahead of time in order to pre-select the epoch would require parsing the query to pull out the measurement. Not something I am eager to do.

Rather, I would like to keep the core `InfluxDB` class as a low-level driver-esque type class, and have `Schema` types act more as traditional models in the future. These schemas would be able handle precision choices more effectively, since the consumer would only be able to call single-measurement operations on each schema (if they want fancy grouped multi-measurement queries they can use the InfluxDB class directly). In this way we can more safely and accurately deal with precisions, and I'm looking forward to the things we'll be able to do in a more model-oriented world.

But, that's for 5.1.
