### ISSUE TITLE
Ensure webpack support is available in 5.0.0

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#221]
I get this when running `.query` in a browser:

> pool.js:232Uncaught (in promise) TypeError: req.setTimeout is not a function(…)

**Comment by connor4312** [comment]
What bundler are you using?

**Comment by dandv** [comment]
Webpack 2

**Comment by connor4312** [comment]
Arg, they're [_still_](https://github.com/webpack/node-libs-browser/issues/38) on the old deprecated http polyfill.

Also, upon further investigation `stream-http` has `req.setTimeout` as a noop, currently. As XHR requests do support setting timeouts, I imagine the issue was that in Node's API `setTimeout` can happen after the `.request()` is made, which XHR doesn't support. However, as you mentioned in another issue Node has modified `http.request` to take a `timeout` option. I'll add a PR into stream-http this evening to support that, then modify this module.

I don't really want to remove http and use some third party module right now, as pending the Webpack PR and my modification to stream-http we should have full support -- hopefully that'll happen by the end of the month when 5.0.0 goes stable. In the interim I will avoid calling `setTimeout` if its `typeof !== 'function'`.

If the webpack folks still haven't merged that PR when 5.0.0 stable is ready, I'll investigate swapping it out for `fetch` or something similar.

**Comment by connor4312** [comment]
PRed in https://github.com/jhiesey/stream-http/pull/55

**Comment by dandv** [comment]
Nice!

BTW, just read that someone managed to [cut the module's size in half](https://github.com/jhiesey/stream-http/issues/45#issuecomment-236328414).

**Comment by connor4312** [comment]
It's not prohibitively difficult to shim the updated stream-http into webpack, as described [here](https://node-influx.github.io/manual/usage.html#browser-setup). (That's actually what we do for browser tests!) As this module does _work_ in Webpack and only needs that shim for timeouts, I would be reasonably comfortable shipping with that setup. We'll see if it's necessary.

**Comment by dandv** [comment]
Is the [browser setup](https://node-influx.github.io/manual/usage.html#browser-setup) section of the docs still necessary now that @jhiesey has [merged your PR](https://github.com/jhiesey/stream-http/commit/f9fb1c724c5a5b900dc651cf0543a227a780d5b3)?

**Comment by connor4312** [comment]
As pointed out in https://github.com/jhiesey/stream-http/issues/66, Node.js just sets a timeout in requests and doesn't worry about actually cancelling the request. Although this behavior seems odd to me, it does mean there's no advantage to trying to force a `timeout`-compatible version of `http` to be used. I'll move away from it and just use a manual `setTimeout` in 5.0.6, upcoming today.
