### ISSUE TITLE
code: 'SELF_SIGNED_CERT_IN_CHAIN' 

### ISSUE THREAD

**Issue by jmikerq** [node-influx/node-influx#260]
Hello,

I am currently using node-influx@4.1.0 and had encounted this error when sending a query to an influx database on Aiven.io

code: 'SELF_SIGNED_CERT_IN_CHAIN'

Is there a way to set influx to ignore this error when creating the InfluxDB object? in the client options maybe?

**Comment by connor4312** [comment]
See http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm and related resources, this is an issue that should be resolved within your node config, not this library.

Thanks for the report!

**Comment by mblackstock** [comment]
@connor4312 thanks for the link, and apologies if I am missing something.  It's not clear to me how this blog post directly relates to this node-influxdb's use of the Node.js https protocol library. 

So, I have the same question.  Does the node-influxdb package pass options to the https protocol it uses?  So far we haven't been able to get this to work.  What I *think* we need is a way to set 'rejectUnauthorized' in the underlying https/tls connection to 'false' so that the certificate is not verified against the list of supplied CAs, avoiding the error when verification fails.  Sorry if I've missed this in the docs.  If there is a better forum for Q&A please let me know.

Thanks again for your help!

**Comment by jmikerq** [comment]
So I just test this in the influx library and it seems remove the error:

in lib/InfluxRequest.js, I added in "rejectUnauthorized:false" in the _defaultRequestOptions_ (line 12) to force the flag(just to test out), then the library doesn't complain about the cert and works fine. I tried this with version 4.1.0, so not sure if you had added that options in the newer version? 

And just as @mblackstock mentioned above, wondering if there is a way to pass that options when using the influx library so we don't have to force this in the _defaultRequestOptions_. Thanks!

**Comment by connor4312** [comment]
I apologize, I should have read a bit more before suggesting an answer :)

I have the option to pass through request options in the [5.1.0](https://github.com/node-influx/node-influx/blob/5.1.0/src/index.ts#L45-L48) branch, however this has not yet been published. There are [other viable options](http://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request?answertab=votes#tab-top) for the moment. You're the second person to request this, so I'll go ahead and get the change backported into a 5.0.x patch and published tonight 😄

**Comment by mblackstock** [comment]
Any progress on this?  I ask only since you'd offered to make the change so quickly :-)

**Comment by connor4312** [comment]
Heyo. Sorry for the delay, I've added this ability in 5.0.5, allowing you to specify the host options in the [constructor config](https://node-influx.github.io/typedef/index.html#static-typedef-IClusterConfig). You can now handle it something like this:

```js
const influx = new InfluxDB({
  hosts: [{
    host: '127.0.0.1',
    port: 1337,
    options: { ca: requestOptionsCA },
  }]
});
```

The `options` get merged down into the options passed to http.request. Let me know if you hit any more snags, thanks for opening the issue!

**Comment by mblackstock** [comment]
thanks - will give it a go!
