### ISSUE TITLE
delete series with delete

### ISSUE THREAD

**Issue by Alwayss** [node-influx/node-influx#279]
Dose this support delete series with delete?

**Comment by connor4312** [comment]
We have a [dropSeries](https://node-influx.github.io/class/src/index.js~InfluxDB.html#instance-method-dropSeries) method. Let me know if you have any other questions!

**Comment by Alwayss** [comment]
But dropSeries does not support time intervals in the where clause.How should I solve this problem

**Comment by sonya** [comment]
@Alwayss is asking about [this query](https://docs.influxdata.com/influxdb/v1.3/query_language/database_management/#delete-series-with-delete), which takes a literal `DELETE` and allows you delete data points within a specific time interval instead of the whole series.

I found that it is possible to do this using [`Pool.json`](https://node-influx.github.io/class/src/pool.js~Pool.html#instance-method-json) or [`Pool.discard`](https://node-influx.github.io/class/src/pool.js~Pool.html#instance-method-discard), but I imagine the Pool functions are not intended to be used by developers this way.


```javascript
var query = "DELETE FROM test WHERE time >= '2017-08-07T18:00:00.000Z' AND time < '2017-08-07T19:00:00.000Z'";

db.pool.json({
    method: 'POST',
    path: '/query',
    query: Object.assign({
        db: 'my_db',
        q: query,
        p: 'testpass',
        precision: 's',
        rp: 'autogen',
        u: 'testuser',
    }),
}).then(function() {
    console.log('success');
});

db.pool.discard({
    method: 'GET', // this should probably be POST, but GET works
    path: '/query',
    query: Object.assign({
        db: 'my_db',
        q: query,
        p: 'testpass',
        precision: 's',
        rp: 'autogen',
        u: 'testuser',
    }),
}).then(function() {
    console.log('success');
});
```

**Comment by sonya** [comment]
Derp, good news, you can actually just use `InfluxDB.query` or `InfluxDB.queryRaw`, i.e.

```javascript
var query = "DELETE FROM test WHERE time >= '2017-08-07T18:00:00.000Z' AND time < '2017-08-07T19:00:00.000Z'";

db.query(query).then(...)
db.queryRaw(query).then(...)
```

I had actually had a misconfiguration in my initialization process and was inadvertently using the pool functions to override the misconfiguration the way you see above.

**Comment by Alwayss** [comment]
I tried it on the way you provided it, it was ok, and thank you very much.

**Comment by Alwayss** [comment]
I tried it on the way you provided it, it was ok, and thank you very much. @sonya
