### ISSUE TITLE
Constructors appear to override previous in index.d.ts

### ISSUE THREAD

**Issue by travissutton** [node-influx/node-influx#280]
I've been using this library for a while, but am just now using this in a node.js/typescript service. I'm sure there are a few variables to this, but it appears that the `index.d.ts` that's being generated is overlapping constructors on the InfluxDB class declaration:

```typescript
constructor(options: ISingleHostConfig);
/**
* Connect to an InfluxDB cluster by specifying a
* set of connection options.
*/
constructor(options: IClusterConfig);
/**
* Connect to an InfluxDB instance using a configuration URL.
* @example
* new InfluxDB('http://user:password@host:8086/database')
*/
constructor(url: string);
/**
* Connects to a local, default Influx instance.
*/
constructor();
```

When I import the library and then type my config, I keep getting type errors complaining that I'm trying to assign a type of `ISingleHostConfig` or `IClusterConfig` to a type of `string`.

Basics of my code:

```typescript
import * as _influx from 'influx';

interface InfluxServiceConfig {
  baseConfig: _influx.ISingleHostConfig | _influx.IClusterConfig | string;
}

class InfluxService {

  private _config: _influx.IClusterConfig | _influx.ISingleHostConfig | string;
  private _client: _influx.InfluxDB;

  constructor(config: InfluxServiceConfig) {
    // assign config
    this._config = config.baseConfig;
  }

  connect() {
    // connect to influx server
    this._client = new _influx.InfluxDB(this._config); // HERE IS WHERE I GET THE TYPE MISMATCHING
  }

}

```

Maybe I'm doing something wrong here, but I use something very similar in other node services albeit in es2015 javascript (no typing).

Shouldn't the declaration follow the documentation and be a single constructor with options being any of the 3 types?

```typescript
constructor(options: ISingleHostConfig | IClusterConfig | string);
```

I'm using node-influx v5.0.7, node 8.0, and Typescript 2.3.1.

Thanks in advance.

**Comment by connor4312** [comment]
Yea, it looks like TS doesn't play nicely with mapping type unions into constructors (discussed in greater depth on https://github.com/Microsoft/TypeScript/issues/1805). It seems reasonable to change the exported signature to be a union rather than an overload.

For the moment, you can of course change that line to

```ts
this._client = new (<any> _influx).InfluxDB(this._config)`
```

**Comment by SPARTAN563** [comment]
Wow, I haven't ever bumped into this. I'll take a look at updating the type signature to avoid this specific issue in future, but I'd ask that we avoid removing the overloaded constructors themselves since they offer a nice, context specific, set of documentation for each case - which is likely to help new user on-boarding more than a generic union type constructor (and its corresponding docs) would.

**Comment by travissutton** [comment]
Thanks @connor4312, I had no idea that was even possible and it corrected the issue. 

Definitely up to you guys on how to handle it. I wasn't aware that could specify that any of the constructors could be used with an `<any>` in front of it. 95% of my TS experience is on the frontend and in cases where I've done different types of params, I've stuck to a union with a single constructor. In reading the documentation (which is great), I thought it was the same until I actually when into the `index.d.ts` file to see what was there.

In any case, thanks for the help and for the education :).
