### ISSUE TITLE
Make default timestamps in Unix Epoch, not RFC3339 format

### ISSUE THREAD

**Issue by NolanChan** [node-influx/node-influx#290]
Hi (again)!,

I was reading the [documentation on influx](https://docs.influxdata.com/influxdb/v1.0/tools/api/#query-string-parameters), and it says that for HTTP requests, I can include the `query` param `epoch=ns` to retrieve my data with `time` in some epoch format like `1503604775` instead of `2017-08-24T19:59:35.000Z`. However, when reading the node-influx docs,  it seems to only mention a `precision` option without allowing me to convert to the `epoch` format that I desire. Is there a way to retrieve the `time`'s in epoch format using node-influx?

Thanks!
Nolan

**Comment by brainsea** [comment]
https://node-influx.github.io/class/src/doc.js~INanoDate.html
You should be able to get the time in epoch format by calling `getTime()` on the time object returned.

**Comment by NolanChan** [comment]
thanks @brainsea !

**Comment by BradfordMedeiros** [comment]
@brainsea  Great library super awesome.  This is the influx library people are coming to as the default node library for influx.  Great job. 

With that, I don't understand why you're transforming the result via the grammar file.  To me it seems like you're needlessly transforming the data.   The way the code is written, it seems like it would make sense to potentially pass a custom data conversion function, but converting the raw result to a iso date object seems very peculiar.

Great job guys, super great job.  Very great.  But would you guys be open to passing the raw epoch result forward instead of adding the extra layer of translation?  Would also be faster for bigger queries.

**Comment by nightwolfz** [comment]
I agree, it makes no sense. Would be nice to have a way circumvent this behavior.

**Comment by bencevans** [comment]
PR welcome :)
