### ISSUE TITLE
Mocking InfluxDB?

### ISSUE THREAD

**Issue by geekdave** [node-influx/node-influx#293]
Hey there.  We're using this library in our code.  We'd like to test that our code is sending proper payloads to InfluxDB during unit tests.  But we want to avoid spinning up an InfluxDB server as a dependency.

I'm looking into tools like [nock](https://github.com/node-nock/nock) which override `http.request`.  But I'm not sure if that would work here since this library does not seem to be using that module.  Any ideas of the best place to mock?

**Comment by connor4312** [comment]
Hey Dave,

Rather than mocking down inside the library, I'd actually recommend mocking Influx itself, for a few reasons.

 - This will usually simplify the mocking/fixture code you need to write
 - You don't need to take on the burden of understanding this library and its internals in order to write mocks
 - We might make changes in this library that are externally non-breaking but change how requests are internally made in some way (e.g. for example, something I've been meaning to do is swap to csv responses over JSON) and you don't want to have to go and fix your tests when this happen.

Let me know if you have any other questions!

**Comment by geekdave** [comment]
Makes sense, @connor4312 !  Any suggestions for how to mock Influx itself?  Would you use a particular mocking library, or roll your own mock?

**Comment by connor4312** [comment]
I've used [Sinon](http://sinonjs.org/) for years with great success, often with [sinon-chai](https://github.com/domenic/sinon-chai). The easiest way to stub the client would be to use [`createStubInstance`](http://sinonjs.org/releases/v3.2.1/stubs/#var-stub--sinonstubobj).

```js
const { expect } = require('chai');
const { InfluxDB } = require('influx');
const sinon = require('sinon');

const myMockDb = sinon.createStubInstance(InfluxDB);
doTheThing(myMockDb);
expect(myMockDb.createDatabase).to.have.been.calledWith('some_db');
```

**Comment by geekdave** [comment]
That's exactly the example I needed.  Thanks so much!
