### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN influxdb   errno: -3001,

### ISSUE THREAD

**Issue by xinmans** [node-influx/node-influx#635]
## Expected Behavior

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: getaddrinfo EAI_AGAIN influxdb
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:72:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'influxdb'
}

Node.js v17.3.1

## Steps/Code to Reproduce the Problem

1. 1. 1.

```
const influx = require('influx')

// ...
```

## Specifications

- Version: Node.js v17.3.1
- Platform: Ubuntu 20.4
- Subsystem:

**Comment by bencevans** [comment]
This appears to be due to resolving `influxdb` from your DNS server, thus the issue lays outside of this library itself. If you're running Influx locally you'll need to replace the hostname with 127.0.0.1 otherwise ensure you can successfully resolve the hostname you're using with tools like dig or ping.

**Comment by xinmans** [comment]
> hostname: 'influxdb'

i just use ip as hostname

**Comment by bencevans** [comment]
@xinmans  Please could you post up the code you're using?
