### ISSUE TITLE
WritePoint and WritePoints do not work with retention policies

### ISSUE THREAD

**Issue by jjfazio** [node-influx/node-influx#85]
If I use writepoint() in the following way

```
db.writePoints('mydb.my_retention_policy.temperature_1d', points, function(err, response) {
      
});
```

Expected:
Insert the points into 'temperature_1d' within 'mydb' using the retention policy 'my_retention_policy'.

Actual:
It creates a new measurement with the name 'mydb.my_retention_policy.temperature_1d' and inserts the points into this new measuremnt with the default retention policy.

**Comment by nichdiekuh** [comment]
I'm afraid you are using it wrong, due to a lack of documentation on our side. 
The retention policy, according to the InfluxDB documentation (https://influxdb.com/docs/v0.9/guides/writing_data.html), is a GET parameter. You can set the retentionpolicy per function call (request) via options.

In your case:
``js
db.writePoints('temperature', points, { rp : 'my_retention_policy'},function(err, response) {

});
``

**Comment by jjfazio** [comment]
Ahh, I was looking for something like that, thank you.

**Comment by nichdiekuh** [comment]
Feel free to reopen this issue if it still doesn't work.
